name: chained

on:
  workflow_run:
    workflows:
      - ci
    types:
      - completed

permissions:
  contents: read

jobs:
  chained:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - run: echo "${ACTOR}"
        env:
          ACTOR: ${{ github.actor }}

