name: PR Preview

on:
  pull_request:
    types:
      - opened

permissions:
  pull-requests: write

jobs:
  pr_preview:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - run: |
          REPO=${{ github.repository }}
          PR_NUMBER=${{ github.event.pull_request.number }}
          gh --repo $REPO pr comment $PR_NUMBER \
            --body "First!"
