name: release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write
  pull-requests: write
  statuses: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
      - uses: actions/setup-node@v4
        with:
          cache: pnpm
      - run: pnpm install
      - uses: changesets/action@v1
        with:
          title: "release: components"
          commit: "release: bump versions"
          publish: |
            pnpm build
            pnpm publish --recursive
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
