name: release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: read
      packages: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          run_install: true
      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version-file: .node-version
          registry-url: 'https://npm.pkg.github.com'
      - run: pnpm build
      - uses: changesets/action@v1
        with:
          commit: 'release: version packages'
          title: 'release: version packages'
          publish: 'pnpm ci:publish'
        env:
          GITHUB_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
