name: release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: read
      packages: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: packages/**/dist
          key: ${{ github.sha }}
          fail-on-cache-miss: true
      - uses: changesets/action@v1
        with:
          commit: 'release: version packages'
          title: 'release: version packages'
          publish: 'pnpm ci:publish'
        env:
          GITHUB_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
